//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitsToday.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HABITS()
        {
            this.HABITLOGS = new HashSet<HABITLOGS>();
        }
    
        public int IDHABITS { get; set; }
        public int IDUSER { get; set; }
        public string HABITNAME { get; set; }
        public string HABITDESCRIPTION { get; set; }
        public string EMOJI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HABITLOGS> HABITLOGS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
