//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitsToday.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HabitsTodayEntities : DbContext
    {
        public HabitsTodayEntities()
            : base("name=HabitsTodayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HABITLOGS> HABITLOGS { get; set; }
        public virtual DbSet<HABITS> HABITS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
